import type { Metadata } from "next";
import { Open_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import TopBarInfoAndLinks from "@/components/shared/TopBarInfoAndLinks";
import Navbar from "@/components/shared/navbar/Navbar";
import Container from "@/components/shared/Container";
import Footer from "@/components/shared/Footer";

const openSans = Open_Sans({
  variable: "--font-openSans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Quite Learning",
    template: "%s | Quite Learning",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} ${montserrat.variable} antialiased`}
      >
        <TopBarInfoAndLinks />
        <div>
          <Navbar />
        </div>
        <Container className="min-h-[calc(100vh-190px)]">{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
